modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MORIMORI0317/BEStyleWither/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "bestylewither"
version = "${version}"
displayName = "BE Style Wither"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/be-style-wither"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/BEStyleWither/main/version_check.json"
authors = "MORIMORI0317"
description = '''
This mod brings the behavior of Wither closer to Bedrock Edition.
The ikisugi wither mod...
'''
logoFile = "icon.png"

[modproperties.bestylewither]
catalogueImageIcon = "icon.png"

[[dependencies.bestylewither]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bestylewither]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"